/*
 * Copyright (C) 2012-2015 Jacob R. Lifshay
 * This file is part of Voxels.
 *
 * Voxels is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Voxels is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Voxels; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 */
#ifndef TEXTURE_ATLAS_H_INCLUDED
#define TEXTURE_ATLAS_H_INCLUDED

#include "texture/texture_descriptor.h"

namespace programmerjake
{
namespace voxels
{
class TextureAtlas final
{
	static Image texture_;
public:
    static const Image &texture();
	const int left, top, width, height;
    const float minU, maxU, minV, maxV;
	enum {textureXRes = 512, textureYRes = 512};
    static constexpr float pixelOffset = 0.05f;
	constexpr TextureAtlas(int left, int top, int width, int height)
        : left(left), top(top), width(width), height(height),
        minU((left + pixelOffset) / textureXRes),
        maxU((left + width - pixelOffset) / textureXRes),
        minV(1 - (top + height - pixelOffset) / textureYRes),
        maxV(1 - (top + pixelOffset) / textureYRes)
	{
	}
	const TextureAtlas & operator =(const TextureAtlas &) = delete;
	TextureDescriptor td() const
	{
		return TextureDescriptor(texture(), minU, maxU, minV, maxV);
	}
	TextureDescriptor tdNoOffset() const
	{
	    return TextureDescriptor(texture(), (float)left / textureXRes, (float)(left + width) / textureXRes, 1 - (float)(top + height) / textureYRes, 1 - (float)top / textureYRes);
	}
	static const TextureAtlas &Fire(int index);
	static int FireFrameCount();
	static const TextureAtlas
	ActivatorRailOff,
    ActivatorRailOn,
    BedHead,
    BedFoot,
    BedTopSide,
    BedTopLeftSide,
    BedTopRightSide,
    BedBottom,
    BedBottomLeftSide,
    BedBottomRightSide,
    BedBottomSide,
    BedItem,
    Font8x8,
    Shockwave,
    Bedrock,
    BirchLeaves,
    BirchPlank,
    BirchSapling,
    BirchWood,
    WoodEnd,
    BlazePowder,
    BlazeRod,
    Bone,
    BoneMeal,
    Bow,
    BrownMushroom,
    Bucket,
    CactusSide,
    CactusBottom,
    CactusTop,
    CactusGreen,
    ChestSide,
    ChestTop,
    ChestFront,
    Cobblestone,
    Coal,
    CoalOre,
    CocoaSmallSide,
    CocoaSmallTop,
    CocoaSmallStem,
    CocoaMediumSide,
    CocoaMediumTop,
    CocoaMediumStem,
    CocoaLargeSide,
    CocoaLargeTop,
    CocoaLargeStem,
    CocoaBeans,
    DeadBush,
    DandelionYellow,
    Dandelion,
    CyanDye,
    Delete0,
    Delete1,
    Delete2,
    Delete3,
    Delete4,
    Delete5,
    Delete6,
    Delete7,
    Delete8,
    Delete9,
    DetectorRailOff,
    DetectorRailOn,
    Diamond,
    DiamondAxe,
    DiamondHoe,
    DiamondOre,
    DiamondPickaxe,
    DiamondShovel,
    Dirt,
    DirtMask,
    DispenserSide,
    DispenserTop,
    DropperSide,
    DropperTop,
    DispenserDropperPistonFurnaceFrame,
    Emerald,
    EmeraldOre,
    PistonBaseSide,
    PistonBaseTop,
    PistonHeadSide,
    PistonHeadFace,
    PistonHeadBase,
    StickyPistonHeadFace,
    FarmlandSide,
    FarmlandTop,
    Fire0,
    Fire1,
    Fire2,
    Fire3,
    Fire4,
    Fire5,
    Fire6,
    Fire7,
    Fire8,
    Fire9,
    Fire10,
    Fire11,
    Fire12,
    Fire13,
    Fire14,
    Fire15,
    Fire16,
    Fire17,
    Fire18,
    Fire19,
    Fire20,
    Fire21,
    Fire22,
    Fire23,
    Fire24,
    Fire25,
    Fire26,
    Fire27,
    Fire28,
    Fire29,
    Fire30,
    Fire31,
    Flint,
    FlintAndSteel,
    FurnaceFrontOff,
    FurnaceSide,
    FurnaceFrontOn,
    WorkBenchTop,
    WorkBenchSide0,
    WorkBenchSide1,
    Glass,
    GoldAxe,
    GoldHoe,
    GoldIngot,
    GoldOre,
    GoldPickaxe,
    GoldShovel,
    GrassMask,
    GrassTop,
    Gravel,
    GrayDye,
    Gunpowder,
    HopperRim,
    HopperInside,
    HopperSide,
    HopperBigBottom,
    HopperMediumBottom,
    HopperSmallBottom,
    HopperItem,
    HotBarBox,
    InkSac,
    IronAxe,
    IronHoe,
    IronIngot,
    IronOre,
    IronPickaxe,
    IronShovel,
    JungleLeaves,
    JunglePlank,
    JungleSapling,
    JungleWood,
    Ladder,
    LapisLazuli,
    LapisLazuliOre,
    WheatItem,
    LavaBucket,
    OakLeaves,
    LeverBaseBigSide,
    LeverBaseSmallSide,
    LeverBaseTop,
    LeverHandleSide,
    LeverHandleTop,
    LeverHandleBottom,
    LightBlueDye,
    LightGrayDye,
    LimeDye,
    MagentaDye,
    MinecartInsideSide,
    MinecartInsideBottom,
    MinecartItem,
    MinecartOutsideLeftRight,
    MinecartOutsideFrontBack,
    MinecartOutsideBottom,
    MinecartOutsideTop,
    MinecartWithChest,
    MinecartWithHopper,
    MinecartWithTNT,
    MobSpawner,
    OrangeDye,
    WaterSide0,
    WaterSide1,
    WaterSide2,
    WaterSide3,
    WaterSide4,
    WaterSide5,
    Obsidian,
    ParticleSmoke0,
    ParticleSmoke1,
    ParticleSmoke2,
    ParticleSmoke3,
    ParticleSmoke4,
    ParticleSmoke5,
    ParticleSmoke6,
    ParticleSmoke7,
    ParticleFire0,
    ParticleFire1,
    PinkDye,
    PinkStone,
    PistonShaft,
    OakPlank,
    PoweredRailOff,
    PoweredRailOn,
    PurpleDye,
    PurplePortal,
    Quartz,
    Rail,
    RailCurve,
    RedMushroom,
    BlockOfRedstone,
    RedstoneComparatorOff,
    RedstoneComparatorOn,
    RedstoneComparatorRepeatorSide,
    RedstoneShortTorchSideOn,
    RedstoneShortTorchSideOff,
    RedstoneDust0,
    RedstoneDust1,
    RedstoneDust2Corner,
    RedstoneDust2Across,
    RedstoneDust3,
    RedstoneDust4,
    RedstoneDustItem,
    RedstoneRepeatorBarSide,
    RedstoneRepeatorBarTopBottom,
    RedstoneRepeatorBarEnd,
    RedstoneOre,
    ActiveRedstoneOre,
    RedstoneRepeatorOff,
    RedstoneRepeatorOn,
    RedstoneTorchSideOn,
    RedstoneTorchSideOff,
    RedstoneTorchTopOn,
    RedstoneTorchTopOff,
    RedstoneTorchBottomOn,
    RedstoneTorchBottomOff,
    Rose,
    RoseRed,
    Sand,
    OakSapling,
    WheatSeeds,
    Shears,
    Slime,
    Snow,
    SnowBall,
    SnowGrass,
    SpruceLeaves,
    SprucePlank,
    SpruceSapling,
    SpruceWood,
    Stick,
    Stone,
    StoneAxe,
    StoneButtonFace,
    StoneButtonLongEdge,
    StoneButtonShortEdge,
    WoodButtonFace,
    WoodButtonLongEdge,
    WoodButtonShortEdge,
    StoneHoe,
    StonePickaxe,
    StonePressurePlateFace,
    StonePressurePlateSide,
    StoneShovel,
    StringItem,
    TallGrass,
    LavaSide0,
    LavaSide1,
    LavaSide2,
    LavaSide3,
    LavaSide4,
    LavaSide5,
    TNTSide,
    TNTTop,
    TNTBottom,
    Blank,
    TorchSide,
    TorchTop,
    TorchBottom,
    Vines,
    WaterBucket,
    SpiderWeb,
    WetFarmland,
    Wheat0,
    Wheat1,
    Wheat2,
    Wheat3,
    Wheat4,
    Wheat5,
    Wheat6,
    Wheat7,
    OakWood,
    WoodAxe,
    WoodHoe,
    WoodPickaxe,
    WoodPressurePlateFace,
    WoodPressurePlateSide,
    WoodShovel,
    Wool,
    Selection,
    Player1HeadFront,
    Player1HeadBack,
    Player1HeadLeft,
    Player1HeadRight,
    Player1HeadTop,
    Player1HeadBottom;
};
}
}

#endif // TEXTURE_ATLAS_H_INCLUDED
